language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/node-server
deploy:
  provider: heroku
  app: chris-notes-server
  api_key:
    secure: q/ybUiYYPZccX0U+Nt2wBNhCzkA0h6bv+rkMZTai12oy/iExtvC7zNKhRkic9U+9QIzvmsXDMVzJ/mx6f2yRBf/tyMcYrD9cib+jiyBLjoP3hKsv3Eb2Wzw6tpLHDRKiC8APjnMotNGojLCNn+ljC4xVPERVmGMLxlIDKZ+dvrk5b7vkp4fD+xJlCx0tVpO07Pp2qn2Ovyxkr/Z2DZAFytVp+YbOR8ADM3OD7kx07MZaib8TbdFIg0kJqN4T82EHNbJi6oOnKTzazQJ/vZH36p+qWueZn85qPoY1oLjc8SqYSzcPsdGoAaSzVoy77iocH+kg7oyovKREyoUKBbuYCR+MJeNcOdSq2cNi/vh8UR3nM6yjEzUzT5+avOrxHZ4491j8lZNRcDla5Uq9Jy0Ew0p7GiYZgQMgsGYbZRKdGLcPZEzaBULW3lE509ZHcHA/ySZ1qikBgzGeLtJKLBgDaIXqoJXjuGU/I4tSwl95R9TEN7L51AcQBkC3NCyIPsV3zQtZHmdrkyfBsQ10XY72wedewyEJ6tTgDMuB4MPaJSbgOBgyP3+j7MwyKA48xtIi4qkyI8i5Tg5yv+r19mdqcIBn4RrhEBcvT7kgtDNSlD3xLtmCa9qm1kuCfdlnGYD7cWETIO9K2RHR/PPxIMMfT9sKGh5frWIPoov2ClsQmNA=
